"""empty message

Revision ID: db0a52dfa80a
Revises: 5f75a7032467
Create Date: 2024-05-27 02:50:21.016162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0a52dfa80a'
down_revision = '5f75a7032467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=80), nullable=False))
        batch_op.drop_column('heigth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('heigth', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('height')

    # ### end Alembic commands ###
